(function(){function h(a){return function(){return this[a]}}var k=this;function n(a){return"string"==typeof a}function p(a,c){var b=a.split("."),d=k;!(b[0]in d)&&d.execScript&&d.execScript("var "+b[0]);for(var f;b.length&&(f=b.shift());)!b.length&&void 0!==c?d[f]=c:d=d[f]?d[f]:d[f]={}};var q="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function s(a){var c=Number(a);return 0==c&&/^[\s\xa0]*$/.test(a)?NaN:c};function t(a,c){this.b=a|0;this.a=c|0}var v={};function w(a){if(-128<=a&&128>a){var c=v[a];if(c)return c}c=new t(a|0,0>a?-1:0);-128<=a&&128>a&&(v[a]=c);return c}function x(a){return isNaN(a)||!isFinite(a)?y:a<=-z?A:a+1>=z?aa:0>a?B(x(-a)):new t(a%C|0,a/C|0)}
function D(a,c){if(0==a.length)throw Error("number format error: empty string");var b=c||10;if(2>b||36<b)throw Error("radix out of range: "+b);if("-"==a.charAt(0))return B(D(a.substring(1),b));if(0<=a.indexOf("-"))throw Error('number format error: interior "-" character: '+a);for(var d=x(Math.pow(b,8)),f=y,e=0;e<a.length;e+=8){var g=Math.min(8,a.length-e),m=parseInt(a.substring(e,e+g),b);8>g?(g=x(Math.pow(b,g)),f=f.multiply(g).add(x(m))):(f=f.multiply(d),f=f.add(x(m)))}return f}
var C=4294967296,z=C*C/2,y=w(0),E=w(1),F=w(-1),aa=new t(-1,2147483647),A=new t(0,-2147483648),G=w(16777216);
t.prototype.toString=function(a){a=a||10;if(2>a||36<a)throw Error("radix out of range: "+a);if(H(this))return"0";if(0>this.a){if(I(this,A)){var c=x(a),b=K(this,c),c=L(b.multiply(c),this);return b.toString(a)+c.b.toString(a)}return"-"+B(this).toString(a)}for(var b=x(Math.pow(a,6)),c=this,d="";;){var f=K(c,b),e=L(c,f.multiply(b)).b.toString(a),c=f;if(H(c))return e+d;for(;6>e.length;)e="0"+e;d=""+e+d}};function M(a){return 0<=a.b?a.b:C+a.b}function H(a){return 0==a.a&&0==a.b}
function I(a,c){return a.a==c.a&&a.b==c.b}function N(a,c){if(I(a,c))return 0;var b=0>a.a,d=0>c.a;return b&&!d?-1:!b&&d?1:0>L(a,c).a?-1:1}function B(a){return I(a,A)?A:(new t(~a.b,~a.a)).add(E)}t.prototype.add=function(a){var c=this.a>>>16,b=this.a&65535,d=this.b>>>16,f=a.a>>>16,e=a.a&65535,g=a.b>>>16,m;m=0+((this.b&65535)+(a.b&65535));a=0+(m>>>16);a+=d+g;d=0+(a>>>16);d+=b+e;b=0+(d>>>16);b=b+(c+f)&65535;return new t((a&65535)<<16|m&65535,b<<16|d&65535)};function L(a,c){return a.add(B(c))}
t.prototype.multiply=function(a){if(H(this)||H(a))return y;if(I(this,A))return 1==(a.b&1)?A:y;if(I(a,A))return 1==(this.b&1)?A:y;if(0>this.a)return 0>a.a?B(this).multiply(B(a)):B(B(this).multiply(a));if(0>a.a)return B(this.multiply(B(a)));if(0>N(this,G)&&0>N(a,G))return x((this.a*C+M(this))*(a.a*C+M(a)));var c=this.a>>>16,b=this.a&65535,d=this.b>>>16,f=this.b&65535,e=a.a>>>16,g=a.a&65535,m=a.b>>>16;a=a.b&65535;var u,l,r,J;J=0+f*a;r=0+(J>>>16);r+=d*a;l=0+(r>>>16);r=(r&65535)+f*m;l+=r>>>16;r&=65535;
l+=b*a;u=0+(l>>>16);l=(l&65535)+d*m;u+=l>>>16;l&=65535;l+=f*g;u+=l>>>16;l&=65535;u=u+(c*a+b*m+d*g+f*e)&65535;return new t(r<<16|J&65535,u<<16|l)};
function K(a,c){if(H(c))throw Error("division by zero");if(H(a))return y;if(I(a,A)){if(I(c,E)||I(c,F))return A;if(I(c,A))return E;var b;b=1;if(0==b)b=a;else{var d=a.a;b=32>b?new t(a.b>>>b|d<<32-b,d>>b):new t(d>>b-32,0<=d?0:-1)}b=K(b,c).shiftLeft(1);if(I(b,y))return 0>c.a?E:F;d=L(a,c.multiply(b));return b.add(K(d,c))}if(I(c,A))return y;if(0>a.a)return 0>c.a?K(B(a),B(c)):B(K(B(a),c));if(0>c.a)return B(K(a,B(c)));for(var f=y,d=a;0<=N(d,c);){b=Math.max(1,Math.floor((d.a*C+M(d))/(c.a*C+M(c))));for(var e=
Math.ceil(Math.log(b)/Math.LN2),e=48>=e?1:Math.pow(2,e-48),g=x(b),m=g.multiply(c);0>m.a||0<N(m,d);)b-=e,g=x(b),m=g.multiply(c);H(g)&&(g=E);f=f.add(g);d=L(d,m)}return f}t.prototype.shiftLeft=function(a){a&=63;if(0==a)return this;var c=this.b;return 32>a?new t(c<<a,this.a<<a|c>>>32-a):new t(0,c<<a-32)};var O=Array.prototype,P=O.forEach?function(a,c,b){O.forEach.call(a,c,b)}:function(a,c,b){for(var d=a.length,f=n(a)?a.split(""):a,e=0;e<d;e++)e in f&&c.call(b,f[e],e,a)},Q=O.map?function(a,c,b){return O.map.call(a,c,b)}:function(a,c,b){for(var d=a.length,f=Array(d),e=n(a)?a.split(""):a,g=0;g<d;g++)g in e&&(f[g]=c.call(b,e[g],g,a));return f};function R(a,c,b){if(a.reduce)return a.reduce(c,b);var d=b;P(a,function(b,e){d=c.call(void 0,d,b,e,a)});return d}
function S(a,c,b){return 2>=arguments.length?O.slice.call(a,c):O.slice.call(a,c,b)};function T(a){return U(1,arguments,function(a,b){return a.add(b)})}function V(a,c){var b=W(2,[a,c]).d;return X(b[0]/b[1])}function Y(a){return U(3,arguments,function(a,b){return L(a,b)})}function Z(a){return U(4,arguments,function(a,b){return a.multiply(b)})}
function $(a){if("number"==typeof a)return a;var c=a.toString(),b=a.c;if(0!=b){var d;a=!1;"-"==c.charAt(0)&&(a=!0,c=c.replace(/^\-/,""));c.length<=b?(c=String(s(c)),d=c.indexOf("."),-1==d&&(d=c.length),b=Math.max(0,b-d),d=Array(b+1).join("0")+c,b="0"):(d=c.slice(-b),b=c.slice(0,-b));c=(a?"-":"")+b+"."+d}return s(c)}function U(a,c,b){c=W(a,c);b=R(S(c.d,1),b,c.d[0]);b.j(a,c.d.length,c.i);return b}
function X(a){if(!n(a)&&"number"!=typeof a)throw Error('Invalid value: "'+a+'"');a=s(String(a));var c=String(a),b,d;if(d=c.match(/\.(\d+)$/)){b=D;var f=RegExp,e;e=".".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08");f=f(e,"");c=c.replace(f,"");b=b(c);b.e(a,d[1].length)}else b=D(c),b.e(a);return b}
function W(a,c){c=Q(c,function(a){return a instanceof t?a:X(a)});if(4==a){var b=R(c,function(a,b){return a+b.c},0);return{d:c,i:b}}var d=Math.max.apply(null,Q(c,function(a){return a.c}));if(0!=d){var f,e;c=Q(c,function(a){f=d-a.c;return 0!=f?(e=a.multiply(x(Math.pow(10,f))),e.k(a),e):a})}return{d:c,i:d}}
(function(a,c){for(var b,d,f=1;f<arguments.length;f++){d=arguments[f];for(b in d)a[b]=d[b];for(var e=0;e<q.length;e++)b=q[e],Object.prototype.hasOwnProperty.call(d,b)&&(a[b]=d[b])}})(t.prototype,{f:void 0,c:0,h:null,g:0,j:function(a,c,b){this.h=a;this.g=c;this.c=b},n:h("h"),m:h("g"),e:function(a,c){a&&(this.f=a);this.c=c||0},k:function(a){this.e(a.f,a.c)},p:h("f"),o:h("c"),l:function(){return 0!=this.c}});
p("sao.calc",function(a){var c,b=[],d=[];P(arguments,function(a){n(a)&&/^\+|\-|\*|\/$/.test(a)?b[b.length]=a:d[d.length]=a});c=R(S(d,1),function(a,c){switch(b.shift()){case "+":return T(a,c);case "-":return Y(a,c);case "/":return V(a,c);case "*":return Z(a,c)}},d[0]);return $(c)});p("sao.add",T);p("sao.div",V);p("sao.sub",Y);p("sao.mul",Z);p("sao.finalize",$);
p("sao.round",function(a,c){var b="number"==typeof a?X(a):a,d=b.toString().replace(/^\-/,""),f=c||0;if(b.l()&&!(b.c<=f)){var e=b.c,d=d.charAt(d.length-e+f),b=X(b.toString().slice(0,-(e-f)));4<s(d)&&(e=x(1),e=0>b.a?B(e):e,b=b.add(e),b.e(void 0,f))}return $(b)});})()
