(function(){function h(a){return function(){return this[a]}}var l=this;function n(a){return"string"==typeof a}function p(a,b){var c=a.split("."),d=l;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&void 0!==b?d[e]=b:d=d[e]?d[e]:d[e]={}};var q="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function s(a){var b=Number(a);return 0==b&&/^[\s\xa0]*$/.test(a)?NaN:b};function t(a,b){this.b=a|0;this.a=b|0}var v={};function w(a){if(-128<=a&&128>a){var b=v[a];if(b)return b}b=new t(a|0,0>a?-1:0);-128<=a&&128>a&&(v[a]=b);return b}function x(a){return isNaN(a)||!isFinite(a)?y:a<=-z?A:a+1>=z?aa:0>a?B(x(-a)):new t(a%C|0,a/C|0)}
function D(a,b){if(0==a.length)throw Error("number format error: empty string");var c=b||10;if(2>c||36<c)throw Error("radix out of range: "+c);if("-"==a.charAt(0))return B(D(a.substring(1),c));if(0<=a.indexOf("-"))throw Error('number format error: interior "-" character: '+a);for(var d=x(Math.pow(c,8)),e=y,f=0;f<a.length;f+=8){var g=Math.min(8,a.length-f),m=parseInt(a.substring(f,f+g),c);8>g?(g=x(Math.pow(c,g)),e=e.multiply(g).add(x(m))):(e=e.multiply(d),e=e.add(x(m)))}return e}
var C=4294967296,z=C*C/2,y=w(0),E=w(1),F=w(-1),aa=new t(-1,2147483647),A=new t(0,-2147483648),G=w(16777216);
t.prototype.toString=function(a){a=a||10;if(2>a||36<a)throw Error("radix out of range: "+a);if(H(this))return"0";if(0>this.a){if(I(this,A)){var b=x(a),c=K(this,b),b=L(c.multiply(b),this);return c.toString(a)+b.b.toString(a)}return"-"+B(this).toString(a)}for(var c=x(Math.pow(a,6)),b=this,d="";;){var e=K(b,c),f=L(b,e.multiply(c)).b.toString(a),b=e;if(H(b))return f+d;for(;6>f.length;)f="0"+f;d=""+f+d}};function M(a){return 0<=a.b?a.b:C+a.b}function H(a){return 0==a.a&&0==a.b}
function I(a,b){return a.a==b.a&&a.b==b.b}function N(a,b){if(I(a,b))return 0;var c=0>a.a,d=0>b.a;return c&&!d?-1:!c&&d?1:0>L(a,b).a?-1:1}function B(a){return I(a,A)?A:(new t(~a.b,~a.a)).add(E)}t.prototype.add=function(a){var b=this.a>>>16,c=this.a&65535,d=this.b>>>16,e=a.a>>>16,f=a.a&65535,g=a.b>>>16,m;m=0+((this.b&65535)+(a.b&65535));a=0+(m>>>16);a+=d+g;d=0+(a>>>16);d+=c+f;c=0+(d>>>16);c=c+(b+e)&65535;return new t((a&65535)<<16|m&65535,c<<16|d&65535)};function L(a,b){return a.add(B(b))}
t.prototype.multiply=function(a){if(H(this)||H(a))return y;if(I(this,A))return 1==(a.b&1)?A:y;if(I(a,A))return 1==(this.b&1)?A:y;if(0>this.a)return 0>a.a?B(this).multiply(B(a)):B(B(this).multiply(a));if(0>a.a)return B(this.multiply(B(a)));if(0>N(this,G)&&0>N(a,G))return x((this.a*C+M(this))*(a.a*C+M(a)));var b=this.a>>>16,c=this.a&65535,d=this.b>>>16,e=this.b&65535,f=a.a>>>16,g=a.a&65535,m=a.b>>>16;a=a.b&65535;var u,k,r,J;J=0+e*a;r=0+(J>>>16);r+=d*a;k=0+(r>>>16);r=(r&65535)+e*m;k+=r>>>16;r&=65535;
k+=c*a;u=0+(k>>>16);k=(k&65535)+d*m;u+=k>>>16;k&=65535;k+=e*g;u+=k>>>16;k&=65535;u=u+(b*a+c*m+d*g+e*f)&65535;return new t(r<<16|J&65535,u<<16|k)};
function K(a,b){if(H(b))throw Error("division by zero");if(H(a))return y;if(I(a,A)){if(I(b,E)||I(b,F))return A;if(I(b,A))return E;var c;c=1;if(0==c)c=a;else{var d=a.a;c=32>c?new t(a.b>>>c|d<<32-c,d>>c):new t(d>>c-32,0<=d?0:-1)}c=K(c,b).shiftLeft(1);if(I(c,y))return 0>b.a?E:F;d=L(a,b.multiply(c));return c.add(K(d,b))}if(I(b,A))return y;if(0>a.a)return 0>b.a?K(B(a),B(b)):B(K(B(a),b));if(0>b.a)return B(K(a,B(b)));for(var e=y,d=a;0<=N(d,b);){c=Math.max(1,Math.floor((d.a*C+M(d))/(b.a*C+M(b))));for(var f=
Math.ceil(Math.log(c)/Math.LN2),f=48>=f?1:Math.pow(2,f-48),g=x(c),m=g.multiply(b);0>m.a||0<N(m,d);)c-=f,g=x(c),m=g.multiply(b);H(g)&&(g=E);e=e.add(g);d=L(d,m)}return e}t.prototype.shiftLeft=function(a){a&=63;if(0==a)return this;var b=this.b;return 32>a?new t(b<<a,this.a<<a|b>>>32-a):new t(0,b<<a-32)};var O=Array.prototype,P=O.forEach?function(a,b,c){O.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=n(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Q=O.map?function(a,b,c){return O.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=n(a)?a.split(""):a,g=0;g<d;g++)g in f&&(e[g]=b.call(c,f[g],g,a));return e};function R(a,b,c){if(a.reduce)return a.reduce(b,c);var d=c;P(a,function(c,f){d=b.call(void 0,d,c,f,a)});return d}
function S(a,b,c){return 2>=arguments.length?O.slice.call(a,b):O.slice.call(a,b,c)};function T(a){return U(1,arguments,function(a,c){return a.add(c)})}function V(a,b){var c=W(2,[a,b]).d;return X(c[0]/c[1])}function Y(a){return U(3,arguments,function(a,c){return L(a,c)})}function Z(a){return U(4,arguments,function(a,c){return a.multiply(c)})}
function $(a){if("number"==typeof a)return a;var b=a.toString(),c=a.c;if(0!=c){var d;a=!1;"-"==b.charAt(0)&&(a=!0,b=b.replace(/^\-/,""));b.length<=c?(b=String(s(b)),d=b.indexOf("."),-1==d&&(d=b.length),c=Math.max(0,c-d),d=Array(c+1).join("0")+b,c="0"):(d=b.slice(-c),c=b.slice(0,-c));b=(a?"-":"")+c+"."+d}return s(b)}function U(a,b,c){b=W(a,b);c=R(S(b.d,1),c,b.d[0]);c.k(a,b.d.length,b.i);return c}
function X(a){if(!n(a)&&"number"!=typeof a)throw Error('Invalid value: "'+a+'"');a=s(String(a));var b=String(a),c,d;if(d=b.match(/\.(\d+)$/)){c=D;var e=RegExp,f;f=".".replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08");e=e(f,"");b=b.replace(e,"");c=c(b);c.f(a,d[1].length)}else c=D(b),c.f(a);return c}
function W(a,b){b=Q(b,function(a){return a instanceof t?a:X(a)});if(4==a){var c=R(b,function(a,c){return a+c.c},0);return{d:b,i:c}}var d=Math.max.apply(null,Q(b,function(a){return a.c}));if(0!=d){var e,f;b=Q(b,function(a){e=d-a.c;return 0!=e?(f=a.multiply(x(Math.pow(10,e))),f.j(a),f):a})}return{d:b,i:d}}
(function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<q.length;f++)c=q[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}})(t.prototype,{e:void 0,c:0,h:null,g:0,k:function(a,b,c){this.h=a;this.g=b;this.c=c},n:h("h"),m:h("g"),f:function(a,b){a&&(this.e=a);this.c=b||0},j:function(a){this.f(a.e,a.c)},p:h("e"),o:h("c"),l:function(){return 0!=this.c}});
p("sao.calc",function(a){var b,c=[],d=[];P(arguments,function(a){n(a)&&/^\+|\-|\*|\/$/.test(a)?c[c.length]=a:d[d.length]=a});b=R(S(d,1),function(a,b){switch(c.shift()){case "+":return T(a,b);case "-":return Y(a,b);case "/":return V(a,b);case "*":return Z(a,b)}},d[0]);return $(b)});p("sao.add",T);p("sao.div",V);p("sao.sub",Y);p("sao.mul",Z);p("sao.finalize",$);
p("sao.round",function(a,b){var c="number"==typeof a?X(a):a,d=c.toString().replace(/^\-/,""),e=b||0;if(c.l()&&!(c.c<=e)){var f=c.c;4<s(d.charAt(d.length-f+e))?(d=c.add(x(Math.pow(10,f-e)*(0>c.a?-1:1))),d.j(c)):d=c;d=$(d);return s(String(d).slice(0,-(f-e)))}return $(c)});})()
